name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-qml:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm qt6-declarative python diffutils git fish

      - name: Check QML format
        shell: fish {0}
        run: |
          /usr/lib/qt6/bin/qmlformat --version
          for file in (string match -v 'build/*' **.qml)
            /usr/lib/qt6/bin/qmlformat $file | diff -u $file - || exit 1
          end
          python3 scripts/qml-lint-conventions.py || true

  check-cpp:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm clang findutils

      - name: Check C++ format
        shell: bash
        run: |
          clang-format --version
          find plugin extras \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format --dry-run --Werror {} +
