name: Lint code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm base-devel cmake ninja gcc clazy qt6-declarative qt6-shadertools python libpipewire aubio libqalculate cava git fish grep

      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clazy -DCMAKE_CXX_FLAGS=-Werror -DVERSION= -DGIT_REVISION=
          cmake --build build

      - name: Lint QML
        shell: fish {0}
        run: |
          /usr/lib/qt6/bin/qmllint --version
          set -l qml_files (string match -vr 'build/.*' **.qml)
          set -l lint_out (/usr/lib/qt6/bin/qmllint --import disable -I build/qml $qml_files 2>&1 | tee /dev/stderr) || true
